### PR TITLE
fix: deps

### PR DESCRIPTION
**Pull request by Ademsk1**
Fixes mdx docs

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
where does this change come from? and how was it done in a way that only affects the lockfile?

**Comment by Ademsk1** [comment]
@simoneb Looks like some dependencies aren't updated when running `npm ci`. I deleted `node_modules` and `package-lock.json`, and then ran `npm i`. Running locally, the docs seem to be fixed. Some of the changes are babel related.

**Comment by simoneb** [comment]
interesting. ok that's the right approach, just wanted to make sure the lockfile wasn't modified manually

**Review by swdilip — APPROVED** [review]
Just tested this and the docs are back up and running! Nicely done 👍🏾

**Pull request merged**
